const fs = require('fs');
const path = require('path');

// Root directory
const rootDir = path.resolve(__dirname, '..');

// Helper to parse a simple .env file without external dependencies
function loadEnvFile(filePath) {
  const envVars = {};
  if (!fs.existsSync(filePath)) return envVars;

  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.substring(0, eqIdx).trim();
    let val = trimmed.substring(eqIdx + 1).trim();

    // Strip surrounding quotes
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }

    envVars[key] = val;
  }

  return envVars;
}

// Load .env and .env.local if present
const localEnv = loadEnvFile(path.join(rootDir, '.env.local'));
const baseEnv = loadEnvFile(path.join(rootDir, '.env'));

// Merge with process.env taking highest priority
function getEnvValue(...keys) {
  for (const key of keys) {
    if (process.env[key] !== undefined && process.env[key] !== '') {
      return process.env[key];
    }
    if (localEnv[key] !== undefined && localEnv[key] !== '') {
      return localEnv[key];
    }
    if (baseEnv[key] !== undefined && baseEnv[key] !== '') {
      return baseEnv[key];
    }
  }
  return '';
}

const supabaseUrl = getEnvValue(
  'SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
  'PUBLIC_SUPABASE_URL',
  'VITE_SUPABASE_URL',
  'NG_APP_SUPABASE_URL'
);

const supabaseKey = getEnvValue(
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_SERVICE_KEY',
  'SUPABASE_SECRET_KEY',
  'SUPABASE_KEY',
  'SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'PUBLIC_SUPABASE_ANON_KEY',
  'VITE_SUPABASE_ANON_KEY',
  'NG_APP_SUPABASE_ANON_KEY'
);

const envDir = path.join(rootDir, 'src', 'environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Write environment.ts (production / default)
const envContent = `// Auto-generated by scripts/set-env.js - DO NOT EDIT DIRECTLY
export const environment = {
  production: true,
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseKey: ${JSON.stringify(supabaseKey)},
  supabaseAnonKey: ${JSON.stringify(supabaseKey)}
};
`;

// Write environment.development.ts
const envDevContent = `// Auto-generated by scripts/set-env.js - DO NOT EDIT DIRECTLY
export const environment = {
  production: false,
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseKey: ${JSON.stringify(supabaseKey)},
  supabaseAnonKey: ${JSON.stringify(supabaseKey)}
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), envContent, 'utf8');
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), envDevContent, 'utf8');

console.log('✅ Environment files generated in src/environments/');
if (supabaseUrl) {
  console.log(`   - Supabase URL: ${supabaseUrl}`);
  console.log(`   - Supabase Key (Service Role / Secret): ${supabaseKey ? '[Configured]' : '[Missing]'}`);
} else {
  console.log('   - Supabase credentials not detected in .env or environment variables.');
  console.log('     Create a .env file or configure SUPABASE_URL & SUPABASE_SERVICE_ROLE_KEY.');
}
